### ISSUE TITLE
Help with nogil-3.12 benchmarks

### ISSUE THREAD

**Issue by xbit18** [colesbury/nogil-3.12-final#7]
Hi @colesbury. I am closely following your work with the free threading python and I'm also writing a thesis on this regard. For this reason I ran benchmarks using pyperformance on different versions of Python and your nogil 3.9 implementation.
I also tried to run it on your 3.12 implementation but some problems arise:
- It's not clear to me which of the two 3.12 nogil repos one should use, [this one](https://github.com/colesbury/nogil-3.12-final) or [this one](https://github.com/colesbury/nogil-3.12-final)?
- What's the current state on the nogil implementation of the above two repos? I tried the other one and it seems to be working by using the PYTHONGIL env variable, but on this one it seems you changed this by using the configuration variable Py_NOGIL, although on my installation it doesn't appear to be having any effect on the use of threads.
- I tried using the other repo (the one that seems to be using free threading) with pyperformance but some problems arise when pyperformance tries to install psutil in the venv. The process exits with an error and the benchmark is skipped. Any pointers to what could be done to avoid this?

I know you are really busy with the 3.13 implementation, I don't want to bother you and thus I don't necessarily expect a fast answer.
Thanks in advance for whatever help you may give me. (forgive my english, I'm not a native speaker)

**Comment by colesbury** [comment]
You should use the https://github.com/colesbury/nogil-3.12 repo. The `nogil-3.12-final` repo was an attempt to rebase the changes onto the actual 3.12 release (nogil-3.12 is based on 3.12.0a4), but it wasn't finished and will probably be abandoned.

https://github.com/colesbury/nogil-3.12 works, but it has a bunch of known bugs that I do not plan to fix. It was primarily intended to support PEP 703. Neither nogil-3.12 nor nogil-3.12-final support extensions well, and you will probably run into problems.

If you want something that works with C extensions, use https://github.com/colesbury/nogil, which is based on Python 3.9

**Comment by xbit18** [comment]
Thank you very much, I'll make due with nogil-3.12. It's probably offtopic here but concerning the current implementation on 3.13 is it already possible to test it or nothing is "out" yet?

**Comment by colesbury** [comment]
It's not ready to be tested yet. Maybe in a few weeks or a month or so.

**Comment by xbit18** [comment]
Good to know, thank you very much!
